# Generated by Django 4.2.7 on 2025-06-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectchecklist_acceptance_criteria_and_more'),
        ('coding', '0012_commandexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('port', models.IntegerField()),
                ('type', models.CharField(default='application', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_config', to='projects.project')),
            ],
            options={
                'db_table': 'server_configs',
                'unique_together': {('project_id', 'port')},
            },
        ),
    ]
