# Generated by Django 4.2.7 on 2026-02-17 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0029_alter_modelselection_selected_model'),
        ('projects', '0061_remove_cli_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_message', models.TextField()),
                ('run_type', models.CharField(choices=[('direct_response', 'Direct Response'), ('research', 'Research Task'), ('single_ticket', 'Single Ticket Execution'), ('pipeline', 'Ticket Pipeline')], default='direct_response', max_length=50)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('executing', 'Executing'), ('waiting_on_user', 'Waiting on User'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('orchestrator_messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='chat.conversation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('execution_type', models.CharField(choices=[('research', 'Research'), ('create_document', 'Create Document'), ('create_prd', 'Create PRD'), ('code_implementation', 'Code Implementation'), ('code_review', 'Code Review'), ('test_writing', 'Test Writing'), ('bug_fix', 'Bug Fix'), ('knowledge_lookup', 'Knowledge Lookup'), ('user_task', 'User Task')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ready', 'Ready'), ('running', 'Running'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('sequence_number', models.IntegerField(default=0)),
                ('worker_context', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('blocked_question', models.TextField(blank=True, null=True)),
                ('user_response', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_executions', to='orchestrator.agentrun')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='blocks', to='orchestrator.ticketexecution')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='projects.projectticket')),
            ],
            options={
                'ordering': ['sequence_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('run_started', 'Run Started'), ('plan_created', 'Plan Created'), ('ticket_dispatched', 'Ticket Dispatched'), ('run_completed', 'Run Completed'), ('run_failed', 'Run Failed'), ('ticket_started', 'Ticket Started'), ('ticket_progress', 'Ticket Progress'), ('ticket_completed', 'Ticket Completed'), ('ticket_failed', 'Ticket Failed'), ('ticket_blocked', 'Ticket Blocked'), ('user_question', 'Question for User'), ('user_response', 'User Response'), ('env_var_needed', 'Environment Variable Needed'), ('env_var_created', 'Environment Variable Created'), ('bug_reported', 'Bug Reported'), ('bug_routed', 'Bug Routed'), ('knowledge_lookup', 'Knowledge Lookup'), ('document_created', 'Document Created')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('requires_user_action', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orchestrator.agentrun')),
                ('ticket_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orchestrator.ticketexecution')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketexecution',
            index=models.Index(fields=['agent_run', 'status'], name='orchestrato_agent_r_8c36d0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketexecution',
            index=models.Index(fields=['status', 'sequence_number'], name='orchestrato_status_6dda3d_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['conversation', 'status'], name='orchestrato_convers_589038_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['project', 'status'], name='orchestrato_project_e6d987_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['agent_run', 'event_type'], name='orchestrato_agent_r_7b4cca_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['requires_user_action', 'created_at'], name='orchestrato_require_e03df9_idx'),
        ),
    ]
