# Generated by Django 4.2.7 on 2026-02-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentevent',
            name='event_type',
            field=models.CharField(choices=[('run_started', 'Run Started'), ('plan_created', 'Plan Created'), ('ticket_dispatched', 'Ticket Dispatched'), ('run_completed', 'Run Completed'), ('run_failed', 'Run Failed'), ('ticket_started', 'Ticket Started'), ('ticket_progress', 'Ticket Progress'), ('ticket_completed', 'Ticket Completed'), ('ticket_failed', 'Ticket Failed'), ('ticket_blocked', 'Ticket Blocked'), ('user_question', 'Question for User'), ('user_response', 'User Response'), ('env_var_needed', 'Environment Variable Needed'), ('env_var_created', 'Environment Variable Created'), ('bug_reported', 'Bug Reported'), ('bug_routed', 'Bug Routed'), ('knowledge_lookup', 'Knowledge Lookup'), ('document_created', 'Document Created'), ('project_ticket_completed', 'Project Ticket Completed'), ('project_ticket_failed', 'Project Ticket Failed'), ('project_ticket_blocked', 'Project Ticket Blocked'), ('preview_check_completed', 'Preview Check Completed')], max_length=50),
        ),
    ]
