# Generated by Django 4.2.7 on 2025-05-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchecklist',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
