# Generated by Django 4.2.7 on 2025-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectimplementation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchecklist',
            name='acceptance_criteria',
            field=models.JSONField(blank=True, default=list, help_text='List of acceptance criteria for ticket completion'),
        ),
        migrations.AddField(
            model_name='projectchecklist',
            name='complexity',
            field=models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('complex', 'Complex')], default='medium', help_text='Estimated complexity of the ticket', max_length=20),
        ),
        migrations.AddField(
            model_name='projectchecklist',
            name='component_specs',
            field=models.JSONField(blank=True, default=dict, help_text='Component-level specifications (buttons, forms, modals, etc.)'),
        ),
        migrations.AddField(
            model_name='projectchecklist',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, help_text='List of ticket IDs or names this ticket depends on'),
        ),
        migrations.AddField(
            model_name='projectchecklist',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed specifications including files, technical requirements'),
        ),
        migrations.AddField(
            model_name='projectchecklist',
            name='requires_worktree',
            field=models.BooleanField(default=True, help_text='Whether this ticket requires a git worktree for code changes'),
        ),
        migrations.AddField(
            model_name='projectchecklist',
            name='ui_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='UI/UX design specifications (layout, colors, typography, spacing, animations)'),
        ),
        migrations.AlterField(
            model_name='projectchecklist',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='open', max_length=20),
        ),
    ]
