# Generated by Django 4.2.7 on 2025-06-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_modelselection_selected_model'),
        ('projects', '0014_projectchecklist_acceptance_criteria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField(blank=True, default=dict)),
                ('generated_content', models.TextField()),
                ('content_type', models.CharField(default='text', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_call_histories', to='chat.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_call_histories', to='chat.message')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_call_histories', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_to_project_79ea1a_idx'), models.Index(fields=['project', 'tool_name'], name='projects_to_project_a19d4a_idx'), models.Index(fields=['conversation', '-created_at'], name='projects_to_convers_973f3e_idx')],
            },
        ),
    ]
