# Generated by Django 4.2.7 on 2025-06-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_toolcallhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='provided_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
