# Generated by Django 4.2.7 on 2025-07-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_provided_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linear_project_id',
            field=models.CharField(blank=True, help_text='Linear project ID for syncing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='linear_sync_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic ticket syncing with Linear'),
        ),
        migrations.AddField(
            model_name='project',
            name='linear_team_id',
            field=models.CharField(blank=True, help_text='Linear team ID for syncing', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projecttickets',
            name='linear_assignee_id',
            field=models.CharField(blank=True, help_text='Linear user ID of assignee', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projecttickets',
            name='linear_issue_id',
            field=models.CharField(blank=True, help_text='Linear issue ID for this ticket', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projecttickets',
            name='linear_issue_url',
            field=models.URLField(blank=True, help_text='Direct URL to the Linear issue', null=True),
        ),
        migrations.AddField(
            model_name='projecttickets',
            name='linear_priority',
            field=models.IntegerField(blank=True, help_text='Priority level from Linear (0-4)', null=True),
        ),
        migrations.AddField(
            model_name='projecttickets',
            name='linear_state',
            field=models.CharField(blank=True, help_text='Current state in Linear (e.g., Todo, In Progress, Done)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttickets',
            name='linear_sync_enabled',
            field=models.BooleanField(default=True, help_text='Whether to sync this specific ticket with Linear'),
        ),
        migrations.AddField(
            model_name='projecttickets',
            name='linear_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this ticket was synced with Linear', null=True),
        ),
    ]
