# Generated by Django 4.2.7 on 2025-07-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_add_linear_fields_to_checklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTickets',
        ),
    ]
