# Generated by Django 4.2.7 on 2025-07-12 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_delete_projecttickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectprd',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='projectprd',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectprd',
            name='name',
            field=models.CharField(default='Main PRD', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectprd',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prds', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectprd',
            unique_together={('project', 'name')},
        ),
    ]
