# Generated by Django 4.2.7 on 2025-07-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_project_id'),
        ('projects', '0020_update_prd_model_for_multiple_prds'),
    ]

    operations = [
    ]
