# Generated by Django 4.2.7 on 2025-07-22 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_merge_20250714_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('prd', 'Product Requirements Document'), ('implementation', 'Technical Implementation Plan'), ('design', 'Design Document'), ('test', 'Test Plan'), ('other', 'Other')], max_length=50)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'file_type', '-created_at'], name='projects_pr_project_3d4205_idx')],
                'unique_together': {('project', 'name', 'file_type')},
            },
        ),
    ]
