# Generated by Django 4.2.7 on 2025-07-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
