# Generated by Django 4.2.7 on 2025-07-23 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0023_projectfile_s3_key_alter_projectfile_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='toolcallhistory',
            name='projects_to_project_79ea1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='toolcallhistory',
            name='projects_to_project_a19d4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='toolcallhistory',
            name='projects_to_convers_973f3e_idx',
        ),
        migrations.AddField(
            model_name='projectfileversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectfileversion',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.projectfile'),
        ),
        migrations.AddIndex(
            model_name='projectfileversion',
            index=models.Index(fields=['file', '-version_number'], name='projects_pr_file_id_2fa6be_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfileversion',
            index=models.Index(fields=['file', '-created_at'], name='projects_pr_file_id_2135b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectfileversion',
            unique_together={('file', 'version_number')},
        ),
    ]
