# Generated by Django 4.2.7 on 2025-08-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_add_file_versioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('prd', 'prd'), ('implementation', 'technical plan'), ('design', 'design'), ('test', 'test plan'), ('other', 'other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='toolcallhistory',
            index=models.Index(fields=['project', '-created_at'], name='projects_to_project_79ea1a_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcallhistory',
            index=models.Index(fields=['project', 'tool_name'], name='projects_to_project_a19d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcallhistory',
            index=models.Index(fields=['conversation', '-created_at'], name='projects_to_convers_973f3e_idx'),
        ),
    ]
