# Generated by Django 4.2.7 on 2025-11-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projectchecklist_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('fail', 'Fail')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Order of task execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('user', 'User')], default='user', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed specifications including files, technical requirements')),
                ('ui_requirements', models.JSONField(blank=True, default=dict, help_text='UI/UX design specifications (layout, colors, typography, spacing, animations)')),
                ('component_specs', models.JSONField(blank=True, default=dict, help_text='Component-level specifications (buttons, forms, modals, etc.)')),
                ('acceptance_criteria', models.JSONField(blank=True, default=list, help_text='List of acceptance criteria for ticket completion')),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of ticket IDs or names this ticket depends on')),
                ('notes', models.TextField(blank=True, default='', help_text='Execution notes, issues, and progress updates for this ticket')),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('complex', 'Complex')], default='medium', help_text='Estimated complexity of the ticket', max_length=20)),
                ('requires_worktree', models.BooleanField(default=True, help_text='Whether this ticket requires a git worktree for code changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linear_issue_id', models.CharField(blank=True, help_text='Linear issue ID for this ticket', max_length=255, null=True)),
                ('linear_issue_url', models.URLField(blank=True, help_text='Direct URL to the Linear issue', null=True)),
                ('linear_state', models.CharField(blank=True, help_text='Current state in Linear (e.g., Todo, In Progress, Done)', max_length=50, null=True)),
                ('linear_priority', models.IntegerField(blank=True, help_text='Priority level from Linear (0-4)', null=True)),
                ('linear_assignee_id', models.CharField(blank=True, help_text='Linear user ID of assignee', max_length=255, null=True)),
                ('linear_synced_at', models.DateTimeField(blank=True, help_text='Last time this ticket was synced with Linear', null=True)),
                ('linear_sync_enabled', models.BooleanField(default=True, help_text='Whether to sync this specific ticket with Linear')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.project')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ProjectChecklist',
        ),
        migrations.AddField(
            model_name='projecttasklist',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projectticket'),
        ),
    ]
