# Generated by Django 4.2.7 on 2025-11-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_projecttasklist_projectticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttasklist',
            name='description',
            field=models.TextField(default='', help_text='Task description (primary field)'),
        ),
        migrations.AlterField(
            model_name='projecttasklist',
            name='name',
            field=models.CharField(blank=True, help_text='Optional task name (deprecated - use description)', max_length=255, null=True),
        ),
    ]
