# Generated by Django 4.2.7 on 2025-11-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_projecttasklist_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttasklist',
            name='name',
        ),
        migrations.AlterField(
            model_name='projecttasklist',
            name='description',
            field=models.TextField(help_text='Task description'),
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(help_text='The command that was executed')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of what this command does', null=True)),
                ('output', models.TextField(blank=True, help_text='Output from the command', null=True)),
                ('exit_code', models.IntegerField(blank=True, help_text='Command exit code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, help_text='Associated task if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='projects.projecttasklist')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.projectticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['ticket'], name='projects_ti_ticket__a1ead9_idx'), models.Index(fields=['task'], name='projects_ti_task_id_6b5753_idx')],
            },
        ),
    ]
