# Generated by Django 4.2.7 on 2025-11-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_projecttasklist_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTaskList',
            new_name='ProjectTodoList',
        ),
    ]
