# Generated by Django 4.2.7 on 2025-11-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_rename_projecttasklist_to_projecttodolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectticket',
            name='github_branch',
            field=models.CharField(blank=True, help_text='Feature branch name for this ticket (e.g., feature/ticket-name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectticket',
            name='github_commit_sha',
            field=models.CharField(blank=True, help_text='Git commit SHA for the ticket implementation', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='projectticket',
            name='github_merge_status',
            field=models.CharField(blank=True, choices=[('merged', 'Merged'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('pending', 'Pending')], help_text='Merge status of feature branch into lfg-agent', max_length=20, null=True),
        ),
    ]
