# Generated by Django 4.2.7 on 2025-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_add_ticket_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='log_type',
            field=models.CharField(choices=[('command', 'Command'), ('user_message', 'User Message'), ('ai_response', 'AI Response')], default='command', help_text='Type of log entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='command',
            field=models.TextField(help_text='The command that was executed (or message content for user/ai messages)'),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='output',
            field=models.TextField(blank=True, help_text='Output from the command (or AI response content)', null=True),
        ),
        migrations.AddIndex(
            model_name='ticketlog',
            index=models.Index(fields=['log_type'], name='projects_ti_log_typ_d9f696_idx'),
        ),
    ]
