# Generated by Django 4.2.7 on 2025-11-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_add_log_type_to_ticketlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectticket',
            name='queue_status',
            field=models.CharField(choices=[('none', 'Not Queued'), ('queued', 'Queued'), ('executing', 'Executing')], default='none', help_text='Current queue status for execution', max_length=20),
        ),
        migrations.AddField(
            model_name='projectticket',
            name='queue_task_id',
            field=models.CharField(blank=True, help_text='Task ID for tracking in the execution queue', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectticket',
            name='queued_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket was added to the execution queue', null=True),
        ),
    ]
