# Generated by Django 4.2.7 on 2025-12-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_add_queue_status_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDesignFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('feature_name', models.CharField(max_length=255)),
                ('feature_description', models.TextField(blank=True, default='')),
                ('explainer', models.TextField(blank=True, default='')),
                ('css_style', models.TextField(blank=True, default='')),
                ('pages', models.JSONField(default=list)),
                ('entry_page_id', models.CharField(blank=True, default='', max_length=100)),
                ('feature_connections', models.JSONField(default=list)),
                ('canvas_position', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_features', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', '-updated_at'], name='projects_pr_project_d14137_idx')],
            },
        ),
    ]
