# Generated by Django 4.2.7 on 2025-12-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_remove_feature_id_add_conversation'),
        ('projects', '0037_projectdesignfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesignfeature',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_features', to='chat.conversation'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdesignfeature',
            unique_together={('project', 'feature_name')},
        ),
        migrations.AddIndex(
            model_name='projectdesignfeature',
            index=models.Index(fields=['project', 'feature_name'], name='projects_pr_project_e0e879_idx'),
        ),
        migrations.RemoveField(
            model_name='projectdesignfeature',
            name='feature_id',
        ),
    ]
