# Generated by Django 4.2.7 on 2025-12-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_remove_feature_id_add_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesignfeature',
            name='common_elements',
            field=models.JSONField(default=list),
        ),
    ]
