# Generated by Django 4.2.7 on 2025-12-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_add_common_elements_to_design_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('feature_positions', models.JSONField(default=dict)),
                ('visible_features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_canvases', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', '-updated_at'], name='projects_de_project_6ca9e9_idx'), models.Index(fields=['project', 'is_default'], name='projects_de_project_547962_idx')],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
