# Generated by Django 4.2.7 on 2025-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_add_design_canvas_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdesignfeature',
            name='platform',
            field=models.CharField(choices=[('web', 'Web (Responsive)'), ('mobile', 'Mobile (iOS)')], default='web', max_length=10),
        ),
    ]
