# Generated by Django 4.2.7 on 2026-01-06 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0041_projectdesignfeature_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Environment variable name (e.g., DATABASE_URL)', max_length=255)),
                ('encrypted_value', models.TextField(help_text='Encrypted value stored securely')),
                ('is_secret', models.BooleanField(default=True, help_text='If true, value is masked in UI')),
                ('description', models.CharField(blank=True, help_text='Optional description of what this variable is for', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_env_vars', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_variables', to='projects.project')),
            ],
            options={
                'verbose_name': 'Environment Variable',
                'verbose_name_plural': 'Environment Variables',
                'ordering': ['key'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
