# Generated by Django 4.2.7 on 2026-01-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_add_environment_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvironmentvariable',
            name='has_value',
            field=models.BooleanField(default=True, help_text='If false, the variable needs a value to be provided by user'),
        ),
        migrations.AddField(
            model_name='projectenvironmentvariable',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If true, this variable is required but may not have a value yet'),
        ),
    ]
