# Generated by Django 4.2.7 on 2026-01-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_add_env_var_required_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order of the stage')),
                ('is_default', models.BooleanField(default=False, help_text='If true, new tickets will be assigned this stage')),
                ('is_completed', models.BooleanField(default=False, help_text='If true, tickets in this stage are considered done')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_stages', to='projects.project')),
            ],
            options={
                'verbose_name': 'Ticket Stage',
                'verbose_name_plural': 'Ticket Stages',
                'ordering': ['order', 'created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='projectticket',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Custom workflow stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='projects.ticketstage'),
        ),
    ]
