# Generated by Django 4.2.7 on 2026-01-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_add_ticket_stage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(choices=[('nextjs', 'Next.js'), ('python-django', 'Python (Django)'), ('python-fastapi', 'Python (FastAPI)'), ('go', 'Go'), ('rust', 'Rust'), ('ruby-rails', 'Ruby on Rails'), ('custom', 'Custom/Existing Repo')], default='nextjs', help_text='Technology stack for this project', max_length=50),
        ),
    ]
