# Generated by Django 4.2.7 on 2026-01-16 09:22

import chat.storage
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_add_execution_time_to_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectticketattachment',
            name='file',
            field=models.FileField(storage=chat.storage.ChatFileStorage(), upload_to=projects.models.get_ticket_attachment_upload_path),
        ),
    ]
