# Generated by Django 4.2.7 on 2026-01-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_alter_projectticketattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectticket',
            name='cli_session_id',
            field=models.CharField(blank=True, help_text='Claude Code CLI session ID for resuming conversations', max_length=100, null=True),
        ),
    ]
