# Generated by Django 4.2.7 on 2026-01-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0051_add_cli_session_id'),
    ]

    operations = [
        # Add 'reverted' to github_merge_status choices (handled by model change)
        migrations.AlterField(
            model_name='projectticket',
            name='github_merge_status',
            field=models.CharField(blank=True, choices=[('merged', 'Merged'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('pending', 'Pending'), ('reverted', 'Reverted')], help_text='Merge status of feature branch into lfg-agent', max_length=20, null=True),
        ),
        # Add merge commit SHA field
        migrations.AddField(
            model_name='projectticket',
            name='github_merge_commit_sha',
            field=models.CharField(blank=True, help_text='The merge commit SHA on lfg-agent branch (for reverting)', max_length=40, null=True),
        ),
        # Add last revert SHA field
        migrations.AddField(
            model_name='projectticket',
            name='github_last_revert_sha',
            field=models.CharField(blank=True, help_text='SHA of the last revert commit (if any)', max_length=40, null=True),
        ),
        # Add reverted_at timestamp
        migrations.AddField(
            model_name='projectticket',
            name='github_reverted_at',
            field=models.DateTimeField(blank=True, help_text='When the merge was last reverted', null=True),
        ),
        # Add reverted_by foreign key
        migrations.AddField(
            model_name='projectticket',
            name='github_reverted_by',
            field=models.ForeignKey(blank=True, help_text='User who reverted the merge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_tickets', to=settings.AUTH_USER_MODEL),
        ),
        # Create TicketMergeHistory model
        migrations.CreateModel(
            name='TicketMergeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('merged', 'Merged'), ('reverted', 'Reverted')], max_length=20)),
                ('merge_commit_sha', models.CharField(help_text='Merge commit SHA on lfg-agent', max_length=40)),
                ('revert_commit_sha', models.CharField(blank=True, help_text='Revert commit SHA (if reverted)', max_length=40, null=True)),
                ('files_changed', models.JSONField(default=list, help_text='List of files changed in the merge')),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_removed', models.IntegerField(default=0)),
                ('commit_message', models.TextField(blank=True, default='')),
                ('commit_author', models.CharField(blank=True, default='', max_length=255)),
                ('commit_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_merge_actions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_history', to='projects.projectticket')),
            ],
            options={
                'verbose_name': 'Ticket Merge History',
                'verbose_name_plural': 'Ticket Merge Histories',
                'ordering': ['-created_at'],
            },
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='ticketmergehistory',
            index=models.Index(fields=['ticket', '-created_at'], name='projects_ti_ticket__e1e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmergehistory',
            index=models.Index(fields=['merge_commit_sha'], name='projects_ti_merge_c_1c9d6f_idx'),
        ),
    ]
