# Generated by Django 4.2.7 on 2026-01-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_add_merge_history_and_revert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketmergehistory',
            new_name='projects_ti_ticket__a0cd9a_idx',
            old_name='projects_ti_ticket__e1e7c2_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmergehistory',
            new_name='projects_ti_merge_c_3ebcc6_idx',
            old_name='projects_ti_merge_c_1c9d6f_idx',
        ),
    ]
