# Generated by Django 4.2.7 on 2026-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_add_cli_task_id_to_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='open', max_length=20),
        ),
    ]
