# Generated by Django 4.2.7 on 2026-01-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_add_preview_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectticket',
            name='linked_documents',
            field=models.ManyToManyField(blank=True, help_text='Documents (PRDs, specs, plans) linked to this ticket', related_name='linked_tickets', to='projects.projectfile'),
        ),
    ]
