# Generated by Django 4.2.7 on 2025-06-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_modelselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_partial',
            field=models.BooleanField(default=False, help_text='Whether this is a partially saved message'),
        ),
        migrations.AddField(
            model_name='message',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='chat_messag_convers_d0740f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_partial'], name='chat_messag_convers_545535_idx'),
        ),
    ]
