# Generated by Django 4.2.7 on 2025-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_message_is_partial_message_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelselection',
            name='selected_model',
            field=models.CharField(choices=[('claude_4_sonnet', 'Claude 4 Sonnet'), ('gpt_4_1', 'OpenAI GPT-4.1'), ('gpt_4o', 'OpenAI GPT-4o'), ('o3', 'OpenAI O3')], default='claude_4_sonnet', max_length=50),
        ),
    ]
