# Generated by Django 4.2.7 on 2025-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_modelselection_selected_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrole',
            name='name',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('product_analyst', 'Analyst'), ('default', 'Default')], default='developer', max_length=50),
        ),
    ]
