# Generated by Django 4.2.7 on 2025-07-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_agentrole_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrole',
            name='turbo_mode',
            field=models.BooleanField(default=False, help_text='Enable turbo mode for quick MVP generation'),
        ),
        migrations.AlterField(
            model_name='modelselection',
            name='selected_model',
            field=models.CharField(choices=[('claude_4_sonnet', 'Claude 4 Sonnet'), ('claude_4_opus', 'Claude 4 Opus'), ('claude_3.5_sonnet', 'Claude 3.5 Sonnet'), ('gpt_4_1', 'OpenAI GPT-4.1'), ('gpt_4o', 'OpenAI GPT-4o'), ('o3', 'OpenAI O3'), ('grok_2', 'Grok 2'), ('grok_beta', 'Grok Beta'), ('grok_4', 'Grok 4')], default='claude_4_sonnet', max_length=50),
        ),
    ]
