# Generated by Django 4.2.7 on 2025-07-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_agentrole_turbo_mode_and_more'),
        ('chat', '0016_alter_agentrole_name_and_more'),
    ]

    operations = [
    ]
