# Generated by Django 4.2.7 on 2025-07-18 21:04

import chat.models
import chat.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_modelselection_selected_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfile',
            name='file',
            field=models.FileField(storage=chat.storage.ChatFileStorage(), upload_to=chat.models.get_file_upload_path),
        ),
    ]
