# Generated by Django 4.2.7 on 2025-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_modelselection_selected_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelselection',
            name='selected_model',
            field=models.CharField(choices=[('claude_4_sonnet', 'Claude 4 Sonnet'), ('claude_4_opus', 'Claude 4 Opus'), ('claude_3.5_sonnet', 'Claude 3.5 Sonnet'), ('gpt-5', 'GPT-5'), ('gpt-5-mini', 'GPT-5-mini'), ('grok_4', 'Grok 4'), ('grok_2', 'Grok 2'), ('grok_beta', 'Grok Beta'), ('gemini_2.5_pro', 'Google Gemini 2.5 Pro'), ('gemini_2.5_flash', 'Google Gemini 2.5 Flash'), ('gemini_2.5_flash_lite', 'Google Gemini 2.5 Flash Lite')], default='claude_4_sonnet', max_length=50),
        ),
    ]
