# Generated by Django 4.2.6 on 2025-08-21 20:15

from django.db import migrations


def update_model_names(apps, schema_editor):
    """Update old OpenAI model names to new ones"""
    ModelSelection = apps.get_model('chat', 'ModelSelection')
    
    # Mapping of old model names to new ones
    model_mapping = {
        'o4-mini': 'gpt-5-mini',
        'o3': 'gpt-5',
        'gpt_4o': 'gpt-5',
        'gpt_4.1': 'gpt-5',
    }
    
    # Update all ModelSelection records
    for old_model, new_model in model_mapping.items():
        ModelSelection.objects.filter(selected_model=old_model).update(selected_model=new_model)


def reverse_model_names(apps, schema_editor):
    """Reverse the model name updates"""
    ModelSelection = apps.get_model('chat', 'ModelSelection')
    
    # Reverse mapping
    model_mapping = {
        'gpt-5-mini': 'o4-mini',
        'gpt-5': 'o3',  # Note: This will lose distinction between gpt_4o, gpt_4.1, and o3
    }
    
    # Update all ModelSelection records
    for new_model, old_model in model_mapping.items():
        ModelSelection.objects.filter(selected_model=new_model).update(selected_model=old_model)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_modelselection_selected_model'),
    ]

    operations = [
        migrations.RunPython(update_model_names, reverse_model_names),
    ]