# Generated by Django 4.2.7 on 2025-11-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_modelselection_selected_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelselection',
            name='selected_model',
            field=models.CharField(choices=[('claude_4_sonnet', 'Sonnet 4'), ('claude_4_haiku', 'Haiku 4'), ('gpt-5', 'GPT-5'), ('gpt-5-mini', 'GPT-5 mini'), ('gemini_2.5_pro', 'Gemini 2.5 Pro'), ('gemini_2.5_flash', 'Gemini 2.5 Flash'), ('gemini_2.5_flash_lite', 'Gemini 2.5 Flash Lite')], default='gpt-5-mini', max_length=50),
        ),
    ]
