# Generated by Django 4.2.7 on 2026-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_add_design_canvas_to_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelselection',
            name='selected_model',
            field=models.CharField(choices=[('claude_4.5_opus', 'Opus 4.5'), ('claude_4.5_sonnet', 'Sonnet 4.5'), ('claude_4.5_haiku', 'Haiku 4.5'), ('gpt-5.2', 'GPT-5.2'), ('gpt-5-mini', 'GPT-5 mini'), ('gemini_3_pro', 'Gemini 3 Pro'), ('gemini_3_flash', 'Gemini 3 Flash'), ('gemini_2.5_flash_lite', 'Gemini 2.5 Flash Lite')], default='gpt-5-mini', max_length=50),
        ),
    ]
