# Generated by Django 4.2.7 on 2025-06-02 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectchecklist_acceptance_criteria_and_more'),
        ('chat', '0011_modelselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_profile_anthropic_api_key_profile_groq_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=20)),
                ('model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4.1', 'GPT-4.1'), ('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-opus-4-20250514', 'Claude Opus 4'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet')], max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_id', models.CharField(blank=True, help_text='Provider request ID for tracking', max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost in USD', max_digits=10, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='chat.conversation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Usage',
                'verbose_name_plural': 'Token Usage Records',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_to_user_id_915aa7_idx'), models.Index(fields=['project', 'timestamp'], name='accounts_to_project_463d6d_idx'), models.Index(fields=['conversation', 'timestamp'], name='accounts_to_convers_6e00ad_idx'), models.Index(fields=['provider', 'model'], name='accounts_to_provide_58cbb8_idx')],
            },
        ),
    ]
