# Generated by Django 4.2.7 on 2025-07-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linear_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
