# Generated by Django 4.2.7 on 2025-07-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_linear_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4.1', 'GPT-4.1'), ('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-opus-4-20250514', 'Claude Opus 4'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('grok-4', 'Grok 4')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('grok', 'Grok')], max_length=20),
        ),
    ]
