# Generated by Django 4.2.7 on 2025-07-17 03:38

from django.db import migrations


def move_linear_api_keys(apps, schema_editor):
    """Move linear API keys from LLMApiKeys to ExternalServicesAPIKeys"""
    # Since the linear_api_key field has already been removed from LLMApiKeys
    # in the previous migration, this data migration is no longer needed.
    # The field removal would have deleted any existing data.
    pass


def reverse_linear_api_keys(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_groq_api_key_llmapikeys_xai_api_key_and_more'),
    ]

    operations = [
        migrations.RunPython(move_linear_api_keys, reverse_linear_api_keys),
    ]