# Generated by Django 4.2.7 on 2025-07-21 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_alter_tokenusage_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_minimized', models.BooleanField(default=False)),
                ('last_selected_model', models.CharField(default='o4-mini', max_length=50)),
                ('last_selected_role', models.CharField(default='product_analyst', max_length=50)),
                ('turbo_mode_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
