# Generated by Django 4.2.7 on 2025-08-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_applicationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmapikeys',
            name='google_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4.1', 'GPT-4.1'), ('o3', 'o3'), ('o4-mini', 'o4 mini'), ('whisper-1', 'Whisper (Audio Transcription)'), ('claude-sonnet-4-20250514', 'Claude Sonnet 4'), ('claude-opus-4-20250514', 'Claude Opus 4'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('grok-4', 'Grok 4'), ('models/gemini-2.5-pro', 'Gemini 2.5 Pro'), ('models/gemini-2.5-flash', 'Gemini 2.5 Flash'), ('models/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('xai', 'XAI'), ('google', 'Google')], max_length=20),
        ),
    ]
