# Generated by Django 4.2.7 on 2025-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_organization_profile_current_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_project_invitations',
            field=models.BooleanField(default=True, help_text='Allow inviting external users to collaborate on projects'),
        ),
    ]