# Generated by Django 4.2.7 on 2025-11-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_allow_project_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmapikeys',
            name='use_personal_llm_keys',
            field=models.BooleanField(default=False),
        ),
    ]
