# Generated by Django 4.2.7 on 2025-11-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_llmapikeys_use_personal_llm_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
