# Generated by Django 4.2.7 on 2025-06-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectchecklist_acceptance_criteria_and_more'),
        ('development', '0013_serverconfig'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='start_server_command',
            field=models.TextField(blank=True, help_text='Command to start the server', null=True),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_configs', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='serverconfig',
            unique_together={('project', 'port')},
        ),
    ]
