# Generated by Django 4.2.7 on 2025-10-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0019_magpieworkspace'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='magpieworkspace',
            new_name='development_project_d660a3_idx',
            old_name='development_magpie_workspace_project_idx',
        ),
        migrations.RenameIndex(
            model_name='magpieworkspace',
            new_name='development_convers_8f4430_idx',
            old_name='development_magpie_workspace_convo_idx',
        ),
        migrations.RenameIndex(
            model_name='magpieworkspace',
            new_name='development_workspa_cbdb1a_idx',
            old_name='development_magpie_workspace_ws_idx',
        ),
        migrations.RenameIndex(
            model_name='magpieworkspace',
            new_name='development_status_7ea843_idx',
            old_name='development_magpie_workspace_status_idx',
        ),
    ]
