# Generated by Django 4.2.7 on 2025-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0020_rename_development_magpie_workspace_project_idx_development_project_d660a3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='ticket_id',
            field=models.IntegerField(blank=True, help_text='Ticket ID that initiated this command', null=True),
        ),
        migrations.AddIndex(
            model_name='commandexecution',
            index=models.Index(fields=['project_id'], name='development_project_8f2cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='commandexecution',
            index=models.Index(fields=['ticket_id'], name='development_ticket__e60858_idx'),
        ),
    ]
