# Generated by Django 4.2.7 on 2025-11-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0021_commandexecution_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandexecution',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation of what this command does', null=True),
        ),
    ]
