# Generated by Django 4.2.7 on 2025-11-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0022_commandexecution_explanation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandExecution',
            new_name='CommandExecutionOld',
        ),
        migrations.RenameIndex(
            model_name='commandexecutionold',
            new_name='development_project_a7cc28_idx',
            old_name='development_project_8f2cbf_idx',
        ),
        migrations.RenameIndex(
            model_name='commandexecutionold',
            new_name='development_ticket__f2c3e7_idx',
            old_name='development_ticket__e60858_idx',
        ),
    ]
