# Generated by Django 4.2.7 on 2026-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0023_rename_commandexecution_commandexecutionold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magpieworkspace',
            name='proxy_url',
            field=models.URLField(blank=True, help_text='Public HTTPS proxy URL for accessing the workspace', max_length=512, null=True),
        ),
    ]
