# Generated by Django 4.2.7 on 2026-01-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('development', '0024_add_proxy_url_to_magpieworkspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='magpieworkspace',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='User associated with this workspace (for user-level workspaces like Claude auth)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='magpie_workspaces',
                to='auth.user'
            ),
        ),
        migrations.AddField(
            model_name='magpieworkspace',
            name='workspace_type',
            field=models.CharField(
                choices=[('execute', 'Ticket Execution'), ('claude_auth', 'Claude Code Auth'), ('preview', 'Preview')],
                default='execute',
                help_text='Purpose of this workspace',
                max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name='magpieworkspace',
            index=models.Index(fields=['user', 'workspace_type'], name='development_user_id_a1b2c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='magpieworkspace',
            constraint=models.UniqueConstraint(
                condition=models.Q(('user__isnull', False)),
                fields=('user', 'workspace_type'),
                name='unique_user_workspace_type'
            ),
        ),
    ]
