# Generated by Django 4.2.7 on 2026-01-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0025_magpieworkspace_type_and_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='magpieworkspace',
            new_name='development_user_id_84f09c_idx',
            old_name='development_user_id_a1b2c3_idx',
        ),
    ]
