# Generated by Django 4.2.7 on 2026-02-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0027_mags_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magpieworkspace',
            name='status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('ready', 'Ready'), ('sleeping', 'Sleeping'), ('stopped', 'Stopped'), ('error', 'Error')], default='provisioning', help_text='Current lifecycle status of the workspace', max_length=20),
        ),
    ]
