# Generated by Django 4.2.7 on 2026-02-16 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_modelselection_selected_model'),
        ('projects', '0061_remove_cli_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('development', '0031_rename_magpieworkspace_to_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('gathering', 'Gathering Requirements'), ('building', 'Building'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='gathering', max_length=20)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('preview_url', models.URLField(blank=True, max_length=512, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='sandbox',
            options={'verbose_name': 'Sandbox', 'verbose_name_plural': 'Sandboxes'},
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='development_project_de2aea_idx',
            old_name='development_project_d660a3_idx',
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='development_convers_a7a2d4_idx',
            old_name='development_convers_8f4430_idx',
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='development_workspa_48ed7d_idx',
            old_name='development_workspa_cbdb1a_idx',
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='development_status_4dea32_idx',
            old_name='development_status_7ea843_idx',
        ),
        migrations.RenameIndex(
            model_name='sandbox',
            new_name='development_user_id_947266_idx',
            old_name='development_user_id_84f09c_idx',
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project associated with this sandbox', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandboxes', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this sandbox (for user-level workspaces like Claude auth)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instantapp',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='instantapp',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_apps', to='projects.project'),
        ),
        migrations.AddField(
            model_name='instantapp',
            name='sandbox',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instant_app', to='development.sandbox'),
        ),
        migrations.AddField(
            model_name='instantapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='instantapp',
            index=models.Index(fields=['project'], name='development_project_9046c3_idx'),
        ),
        migrations.AddIndex(
            model_name='instantapp',
            index=models.Index(fields=['user'], name='development_user_id_88450e_idx'),
        ),
        migrations.AddIndex(
            model_name='instantapp',
            index=models.Index(fields=['status'], name='development_status_23c82f_idx'),
        ),
    ]
