# Generated by Django 4.2.7 on 2026-02-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0032_instantapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='workspace_type',
            field=models.CharField(choices=[('execute', 'Ticket Execution'), ('ticket', 'Ticket'), ('instant', 'Instant App'), ('claude_auth', 'Claude Code Auth'), ('preview', 'Preview')], default='execute', help_text='Purpose of this workspace', max_length=20),
        ),
    ]
