# Generated by Django 4.2.7 on 2026-02-18 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_remove_cli_fields'),
        ('development', '0033_add_ticket_instant_workspace_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantapp',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instant_apps', to='projects.project'),
        ),
    ]
