# Generated by Django 4.2.7 on 2025-10-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase_index', '0002_codebaseindexmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedrepository',
            name='codebase_summary',
            field=models.TextField(blank=True, help_text='AI-generated comprehensive summary of the codebase', null=True),
        ),
        migrations.AddField(
            model_name='indexedrepository',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the summary was generated', null=True),
        ),
    ]
