# Generated by Django 4.2.7 on 2025-12-06 21:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codebase_index', '0003_add_codebase_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedrepository',
            name='is_frontend',
            field=models.BooleanField(default=False, help_text='Whether this is a frontend repository for UI indexing'),
        ),
        migrations.CreateModel(
            name='FrontendScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(help_text="Screen/page name (e.g., 'Login', 'Dashboard')", max_length=255)),
                ('route', models.CharField(blank=True, help_text="Route path (e.g., '/login', '/dashboard')", max_length=500, null=True)),
                ('file_path', models.CharField(help_text='Main file path for this screen', max_length=1000)),
                ('screen_type', models.CharField(default='page', help_text='Type: page, modal, drawer, etc.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='AI-generated description of screen purpose', null=True)),
                ('component_files', models.JSONField(default=list, help_text='List of component files used in this screen')),
                ('style_files', models.JSONField(default=list, help_text='List of CSS/style files for this screen')),
                ('linked_screens', models.JSONField(default=list, help_text='List of screen IDs this screen navigates to')),
                ('framework', models.CharField(blank=True, help_text='Detected framework: react, vue, angular, etc.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_screen', models.ForeignKey(blank=True, help_text='Parent screen for nested routes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_screens', to='codebase_index.frontendscreen')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_screens', to='codebase_index.indexedrepository')),
            ],
            options={
                'verbose_name': 'Frontend Screen',
                'verbose_name_plural': 'Frontend Screens',
            },
        ),
        migrations.CreateModel(
            name='FrontendIndexingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('total_screens', models.IntegerField(default=0)),
                ('total_components', models.IntegerField(default=0)),
                ('total_routes', models.IntegerField(default=0)),
                ('total_navigation_links', models.IntegerField(default=0)),
                ('detected_framework', models.CharField(blank=True, max_length=50, null=True)),
                ('framework_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ui_library', models.CharField(blank=True, help_text='e.g., Material UI, Tailwind, Bootstrap', max_length=100, null=True)),
                ('ui_structure_summary', models.TextField(blank=True, help_text='AI summary of overall UI structure', null=True)),
                ('navigation_flow', models.JSONField(default=dict, help_text='Graph of screen navigation flow')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_index_status', to='codebase_index.indexedrepository')),
            ],
            options={
                'verbose_name': 'Frontend Indexing Status',
                'verbose_name_plural': 'Frontend Indexing Statuses',
            },
        ),
        migrations.CreateModel(
            name='FrontendUIComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(help_text='Component name or label', max_length=255)),
                ('component_type', models.CharField(choices=[('button', 'Button'), ('link', 'Link'), ('input', 'Input Field'), ('form', 'Form'), ('modal', 'Modal'), ('dropdown', 'Dropdown'), ('menu', 'Menu'), ('nav', 'Navigation'), ('card', 'Card'), ('list', 'List'), ('table', 'Table'), ('tab', 'Tab'), ('accordion', 'Accordion'), ('toast', 'Toast/Notification'), ('icon', 'Icon'), ('image', 'Image'), ('text', 'Text/Label'), ('container', 'Container'), ('custom', 'Custom Component')], default='custom', max_length=50)),
                ('file_path', models.CharField(help_text='File where component is defined', max_length=1000)),
                ('start_line', models.IntegerField(help_text='Starting line in file')),
                ('end_line', models.IntegerField(help_text='Ending line in file')),
                ('label_text', models.CharField(blank=True, help_text='Display text/label', max_length=500, null=True)),
                ('css_classes', models.JSONField(default=list, help_text='CSS classes applied')),
                ('props', models.JSONField(default=dict, help_text='Component props/attributes')),
                ('action_type', models.CharField(choices=[('navigate', 'Navigate to Screen'), ('submit', 'Submit Form'), ('api_call', 'API Call'), ('modal_open', 'Open Modal'), ('modal_close', 'Close Modal'), ('toggle', 'Toggle State'), ('download', 'Download'), ('upload', 'Upload'), ('external_link', 'External Link'), ('none', 'No Action')], default='none', max_length=50)),
                ('action_target', models.CharField(blank=True, help_text='Target route, API endpoint, or screen ID', max_length=500, null=True)),
                ('is_interactive', models.BooleanField(default=False, help_text='Whether this component is interactive')),
                ('is_primary_action', models.BooleanField(default=False, help_text='Whether this is a primary CTA')),
                ('accessibility_label', models.CharField(blank=True, help_text='Aria-label or similar', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('navigates_to', models.ForeignKey(blank=True, help_text='Screen this component navigates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_navigation', to='codebase_index.frontendscreen')),
                ('parent_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='codebase_index.frontenduicomponent')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='codebase_index.frontendscreen')),
            ],
            options={
                'verbose_name': 'Frontend UI Component',
                'verbose_name_plural': 'Frontend UI Components',
                'indexes': [models.Index(fields=['screen', 'component_type'], name='codebase_in_screen__a8647e_idx'), models.Index(fields=['action_type'], name='codebase_in_action__08b284_idx'), models.Index(fields=['is_interactive'], name='codebase_in_is_inte_b92603_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='frontendscreen',
            index=models.Index(fields=['repository', 'screen_type'], name='codebase_in_reposit_d1c01f_idx'),
        ),
        migrations.AddIndex(
            model_name='frontendscreen',
            index=models.Index(fields=['repository', 'route'], name='codebase_in_reposit_491d84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frontendscreen',
            unique_together={('repository', 'file_path')},
        ),
    ]
