# Generated by Django 4.2.7 on 2025-12-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase_index', '0004_add_frontend_ui_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexedrepository',
            name='app_url',
            field=models.URLField(blank=True, help_text='Live application URL (e.g., https://myapp.com) for previewing existing screens', null=True),
        ),
    ]
