# Generated by Django 4.2.7 on 2025-12-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codebase_index', '0005_add_app_url_to_indexed_repository'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frontendscreen',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='frontendscreen',
            name='parent_screen',
        ),
        migrations.RemoveField(
            model_name='frontendscreen',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='frontenduicomponent',
            name='navigates_to',
        ),
        migrations.RemoveField(
            model_name='frontenduicomponent',
            name='parent_component',
        ),
        migrations.RemoveField(
            model_name='frontenduicomponent',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='indexedrepository',
            name='app_url',
        ),
        migrations.RemoveField(
            model_name='indexedrepository',
            name='is_frontend',
        ),
        migrations.DeleteModel(
            name='FrontendIndexingStatus',
        ),
        migrations.DeleteModel(
            name='FrontendScreen',
        ),
        migrations.DeleteModel(
            name='FrontendUIComponent',
        ),
    ]
