# Generated by Django 4.2.7 on 2026-02-18 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0061_remove_cli_fields'),
        ('chat', '0029_alter_modelselection_selected_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Telegram Bot API token', max_length=512)),
                ('bot_username', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Encrypted Slack Bot OAuth token', max_length=512)),
                ('team_id', models.CharField(blank=True, default='', max_length=64)),
                ('team_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('slack', 'Slack'), ('telegram', 'Telegram')], max_length=16)),
                ('channel_id', models.CharField(help_text='Slack channel ID or Telegram chat ID', max_length=128)),
                ('channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, help_text='Reusable conversation for this channel link', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_link', to='chat.conversation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_links', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('content', models.TextField()),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='integrations.channelprojectlink')),
                ('message', models.ForeignKey(blank=True, help_text='Linked LFG chat message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_messages', to='chat.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='channelprojectlink',
            index=models.Index(fields=['platform', 'channel_id'], name='integration_platfor_da6f65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelprojectlink',
            unique_together={('user', 'platform', 'channel_id')},
        ),
        migrations.AddIndex(
            model_name='channelmessage',
            index=models.Index(fields=['channel_link', '-created_at'], name='integration_channel_13b17d_idx'),
        ),
    ]
