# Generated by Django 4.2.7 on 2025-08-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20250418_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='monthly_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercredit',
            name='monthly_tokens_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercredit',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free Tier'), ('pro', 'Pro Monthly')], default='free', max_length=50),
        ),
        migrations.AddField(
            model_name='usercredit',
            name='total_tokens_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
