# Generated by Django 4.2.7 on 2025-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_usercredit_monthly_reset_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='free_tokens_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercredit',
            name='paid_tokens_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
