# Generated by Django 4.2.7 on 2025-08-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_organization_profile_current_organization_and_more'),
        ('subscriptions', '0004_usercredit_free_tokens_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits_added', models.BigIntegerField(default=0)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_period_start', models.DateTimeField(blank=True, null=True)),
                ('billing_period_end', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.organization')),
                ('payment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.paymentplan')),
            ],
            options={
                'verbose_name': 'Organization Transaction',
                'verbose_name_plural': 'Organization Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.BigIntegerField(default=0)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('total_tokens_used', models.BigIntegerField(default=0)),
                ('monthly_tokens_used', models.BigIntegerField(default=0)),
                ('monthly_reset_date', models.DateTimeField(blank=True, null=True)),
                ('free_tokens_used', models.BigIntegerField(default=0)),
                ('paid_tokens_used', models.BigIntegerField(default=0)),
                ('subscription_tier', models.CharField(choices=[('org_free', 'Organization Free'), ('org_pro', 'Organization Pro')], default='org_pro', max_length=50)),
                ('seat_count', models.PositiveIntegerField(default=1)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='accounts.organization')),
            ],
        ),
    ]
