# Generated by Django 4.2.7 on 2025-08-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_organizationtransaction_organizationcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
